spring.application.name=producer
server.port=8081

spring.kafka.bootstrap-servers=kafka-1:29092,kafka-2:29092,kafka-3:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

monitor.url=http://monitor:8085
